version: '3'
services:

  mongodb:
    image: mongo:3.4
    ports:
      - "9998:27017"

  www:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5858:5858"
      - "9999:9999"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - DG_LOGGING_STREAMS_STDOUT_LEVEL=debug
      - DB_SERVER_PRETTY_OUTPUT=true
    volumes:
      - .:/opt/app
    command: /bin/bash -c 'npm install && npm run serve'
